# Generated by Django 2.0.9 on 2019-01-02 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steamkeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamkey',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='steamkey',
            name='given_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steamkey',
            name='given_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='steamkey',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
