# Generated by Django 2.0.9 on 2019-01-02 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('steamkeys', '0004_steamkey_gift_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamkey',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='steamkey',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
