# Generated by Django 2.0.9 on 2019-01-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamkeys', '0005_auto_20190102_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamkey',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='steamkey',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
